/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.lib

import org.junit.Test


class LibraryTest {
	@Test
	fun testSomeLibraryMethod() {
		val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
	}
}
